######################################################################
# Automatically generated by qmake (3.0) Mon Feb 1 15:18:06 2016
######################################################################

QT += widgets opengl
TEMPLATE = app
TARGET = pplot
INCLUDEPATH += ./

# Input
HEADERS += openglwindow.h model.h
SOURCES += main.cpp openglwindow.cpp model.cpp
MOC_DIR = .moc/
OBJECTS_DIR = .objects/
